name: fitrecipe_hellmill
description: Fitrecipe – Hellmill (Flutter, Android) – Tabata, heti terv, checklist, időzítő, QR megosztás
publish_to: "none"
version: 1.0.3+103

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.2.2
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
